const itineraries = [
  {
    id: 1,
    title: "Salim Ali Bird Sanctuary",
    interest: "Adventure",
    time: 2,
    region: "North Goa",
    triplength: "1-3 days",
    location: "north",
    address: "Near island of Chorao, Goa",
    budget: 1200,
    desc:
      "A popular sanctuary for bird lovers, especially during migratory seasons.",
    photo: "/tour-images/salim-ali.jpg",
    offer: false,
    details:
      "Located in the Mandovi River estuary, the sanctuary hosts a variety of rare and migratory birds.",
  },
  {
    id: 2,
    title: "Baga Beach",
    interest: "Nightlife",
    time: 3,
    region: "North Goa",
    triplength: "1-3 days",
    location: "north",
    address: "Bardez, North Goa",
    budget: 1500,
    desc: "A famous beach with exciting nightlife and water sports activities.",
    photo: "/tour-images/baga-beach.jpg",
    offer: true,
    details:
      "Ideal for parties and adventure seekers with an amazing coastal experience.",
  },
  {
    id: 3,
    title: "Fort Aguada",
    interest: "Cultural",
    time: 1,
    region: "North Goa",
    triplength: "11-14 days",
    location: "north",
    address: "Candolim, North Goa",
    budget: 500,
    desc:
      "A 17th-century Portuguese fort with stunning views of the Arabian Sea.",
    photo: "/tour-images/fort-aguada.jpg",
    offer: false,
    details:
      "The fort also houses a lighthouse that provides a spectacular view.",
  },
  {
    id: 4,
    title: "Dudhsagar Waterfalls",
    interest: "Nature",
    time: 4,
    region: "South Goa",
    triplength: "4-7 days",
    location: "south",
    address: "Sonaulim, Goa",
    budget: 1800,
    desc: "A mesmerizing four-tiered waterfall located on the Mandovi River.",
    photo: "/tour-images/dudhsagar.jpg",
    offer: false,
    details: "A breathtaking view for nature lovers and trekkers.",
  },
  {
    id: 5,
    title: "Palolem Beach",
    interest: "Relaxation",
    time: 2,
    region: "South Goa",
    triplength: "4-7 days",
    location: "south",
    address: "Canacona, South Goa",
    budget: 2000,
    desc: "A serene beach perfect for relaxation and water adventures.",
    photo: "/tour-images/palolem-beach.jpg",
    offer: true,
    details: "Enjoy dolphin-spotting tours and soothing sunsets.",
  },
  {
    id: 6,
    title: "Margao Market",
    interest: "Shopping",
    time: 1,
    region: "South Goa",
    triplength: "15+ Days",
    location: "south",
    address: "Margao, South Goa",
    budget: 800,
    desc:
      "An authentic Goan market experience with local produce and souvenirs.",
    photo: "/tour-images/margao-market.jpg",
    offer: true,
    details: "Shop for spices, pottery, and unique Goan handicrafts.",
  },
];

export default itineraries;
